CSS and HBS for ESMF website in regards to landing page redesign
bci-oss/esmf-antora-ui pull request #10
Opened 2023-12-15 08:59 UTC by anastascho

This is the current state of all css and hbs changes intended for the ESMF landing page redesign.
Please review them, but keep in mind that this is still in progress.

2023-12-15 09:04 UTC, anastascho commented
Here you can find a snapshot of the current state of the landing page:

http://fe0vm2112.de.bosch.com/doku/bosch-semantic-stack/ESMF/site/site/esmf-documentation/index.html

2023-12-21 10:41 UTC, aniluede requested changes
two links to be updated

2023-12-21 10:41 UTC, aniluede commented on src/partials/sections-nav-mobile.hbs
> +          <li><a href="https://projects.eclipse.org/proposals/eclipse-semantic-modeling-framework-esmf" target="_blank">About ESMF</a></li>
```suggestion
          <li><a href="https://projects.eclipse.org/projects/dt.esmf" target="_blank">About ESMF</a></li>
```

2023-12-21 10:41 UTC, aniluede commented on src/partials/sections-header-content.hbs
> +          <li><a href="https://projects.eclipse.org/proposals/eclipse-semantic-modeling-framework-esmf" target="_blank">About ESMF</a></li>
```suggestion
          <li><a href="https://projects.eclipse.org/projects/dt.esmf" target="_blank">About ESMF</a></li>
```

2023-12-21 11:57 UTC, aniluede approved these changes
LGTM

2023-12-21 12:21 UTC, merged